#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
client:
 tls:
  enabled: false

 security:
  enabled: true
  hashAlgorithm: "SHA2"
  level: 256

 tcert:
  batch:
    size: 200

 logging:
  level: info

 keystore:
  path: msp

 cryptoconfig:
  path: "conf/crypto-config"

 connection:
   timeout:
    peer:
     endorser: 5s
     eventHub: 5s
     eventReg: 5s
     orderer: 5s

# network provides a static definition of a Hyperledger Fabric network
 network:
  # list of ordering service nodes
  orderers:
   # orderer name
   orderer0:
    host: "47.92.106.133"
    port: 7050
    tls:
     # Certificate location absolute path
     certificate: "conf/crypto-config/ordererOrganizations/example.com/tlsca/tlsca.example.com-cert.pem"
     # For testing only: overrides the virtual host name of the authority
     serverHostOverride: "orderer.example.com"
  # ap of member organizations forming the network
  organizations:
    # Org1 name
    peerorg1:
      # Membership Service Provider ID for this organization
      mspID: "Org1MSP"
      # CA config defines the fabric-ca instance that issues identities for this org
      ca:
       # TLS secured connections with the CA
       tlsEnabled: false
       # CA name
       name: "ca-org1"
       # CA URL. Note: https prefix required for TLS
       #serverURL: "http://127.0.0.1:7054"
       serverURL:  "http://47.92.106.133:7054"
       # Configuration for mutual TLS with the CA
       tls:
        # Comma-Separated list of paths
        certfiles : "$GOPATH/src/github.com/hyperledger/fabric-sdk-go/test/fixtures/tls/fabricca/ca/ca_root.pem"
        client:
         keyfile: "$GOPATH/src/github.com/hyperledger/fabric-sdk-go/test/fixtures/tls/fabricca/client/client_client1-key.pem"
         certfile: "$GOPATH/src/github.com/hyperledger/fabric-sdk-go/test/fixtures/tls/fabricca/client/client_client1.pem"
      # Peers that are part of this organization
      peers:
       # Peer name
       peer0:
        host: "47.92.98.167"
        port: 7051
        eventHost: "47.92.98.167"
        eventPort: 7053
        primary: true
        tls:
         # Certificate location absolute path
         certificate: "conf/crypto-config/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem"
         serverHostOverride: "peer0.org1.example.com"
    # Org2
    peerorg2:
      mspID: "Org2MSP"
      ca:
       tlsEnabled: false
       name: "ca-org2"
       serverURL: "http://47.92.73.251:7054"
       tls:
        # Comma-Separated list of paths
        certfiles : "$GOPATH/src/github.com/hyperledger/fabric-sdk-go/test/fixtures/tls/fabricca/ca/ca_root.pem"
        client:
         keyfile: "$GOPATH/src/github.com/hyperledger/fabric-sdk-go/test/fixtures/tls/fabricca/client/client_client1-key.pem"
         certfile: "$GOPATH/src/github.com/hyperledger/fabric-sdk-go/test/fixtures/tls/fabricca/client/client_client1.pem"
      peers:
       peer0:
        host: "47.52.27.118"
        port: 7051
        eventHost: "47.52.27.118"
        eventPort: 7053
        primary: true
        tls:
         # Certificate location absolute path
         certificate: "conf/crypto-config/peerOrganizations/org2.example.com/tlsca/tlsca.org2.example.com-cert.pem"
         serverHostOverride: "peer0.org2.example.com"
