// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stream.pro

/*
Package stream is a generated protocol buffer package.

It is generated from these files:
	stream.pro

It has these top-level messages:
	RegisterRequest
	RegisterReply
	AssetEnroll
	AssetRegister
	AssetQuery
	Transaction
	ResultsReply
*/
package stream

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RegisterRequest struct {
	User        string `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Pwd         string `protobuf:"bytes,2,opt,name=pwd" json:"pwd,omitempty"`
	Org         string `protobuf:"bytes,3,opt,name=org" json:"org,omitempty"`
	Affiliation string `protobuf:"bytes,4,opt,name=affiliation" json:"affiliation,omitempty"`
}

func (m *RegisterRequest) Reset()                    { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()               {}
func (*RegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RegisterRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *RegisterRequest) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

func (m *RegisterRequest) GetOrg() string {
	if m != nil {
		return m.Org
	}
	return ""
}

func (m *RegisterRequest) GetAffiliation() string {
	if m != nil {
		return m.Affiliation
	}
	return ""
}

type RegisterReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Appid   string `protobuf:"bytes,2,opt,name=appid" json:"appid,omitempty"`
	Appkey  string `protobuf:"bytes,3,opt,name=appkey" json:"appkey,omitempty"`
	Prikey  string `protobuf:"bytes,4,opt,name=prikey" json:"prikey,omitempty"`
	Cert    string `protobuf:"bytes,5,opt,name=cert" json:"cert,omitempty"`
}

func (m *RegisterReply) Reset()                    { *m = RegisterReply{} }
func (m *RegisterReply) String() string            { return proto.CompactTextString(m) }
func (*RegisterReply) ProtoMessage()               {}
func (*RegisterReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RegisterReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RegisterReply) GetAppid() string {
	if m != nil {
		return m.Appid
	}
	return ""
}

func (m *RegisterReply) GetAppkey() string {
	if m != nil {
		return m.Appkey
	}
	return ""
}

func (m *RegisterReply) GetPrikey() string {
	if m != nil {
		return m.Prikey
	}
	return ""
}

func (m *RegisterReply) GetCert() string {
	if m != nil {
		return m.Cert
	}
	return ""
}

type AssetEnroll struct {
	Channel          string `protobuf:"bytes,1,opt,name=channel" json:"channel,omitempty"`
	Chaincodepath    string `protobuf:"bytes,2,opt,name=chaincodepath" json:"chaincodepath,omitempty"`
	Chaincode        string `protobuf:"bytes,3,opt,name=chaincode" json:"chaincode,omitempty"`
	Chaincodeversion string `protobuf:"bytes,4,opt,name=chaincodeversion" json:"chaincodeversion,omitempty"`
	Key              string `protobuf:"bytes,5,opt,name=key" json:"key,omitempty"`
	Payload          string `protobuf:"bytes,6,opt,name=payload" json:"payload,omitempty"`
}

func (m *AssetEnroll) Reset()                    { *m = AssetEnroll{} }
func (m *AssetEnroll) String() string            { return proto.CompactTextString(m) }
func (*AssetEnroll) ProtoMessage()               {}
func (*AssetEnroll) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AssetEnroll) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *AssetEnroll) GetChaincodepath() string {
	if m != nil {
		return m.Chaincodepath
	}
	return ""
}

func (m *AssetEnroll) GetChaincode() string {
	if m != nil {
		return m.Chaincode
	}
	return ""
}

func (m *AssetEnroll) GetChaincodeversion() string {
	if m != nil {
		return m.Chaincodeversion
	}
	return ""
}

func (m *AssetEnroll) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *AssetEnroll) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type AssetRegister struct {
	Channel   string `protobuf:"bytes,1,opt,name=channel" json:"channel,omitempty"`
	Chaincode string `protobuf:"bytes,2,opt,name=chaincode" json:"chaincode,omitempty"`
	Appid     string `protobuf:"bytes,3,opt,name=appid" json:"appid,omitempty"`
	Key       string `protobuf:"bytes,4,opt,name=key" json:"key,omitempty"`
	Payload   string `protobuf:"bytes,5,opt,name=payload" json:"payload,omitempty"`
}

func (m *AssetRegister) Reset()                    { *m = AssetRegister{} }
func (m *AssetRegister) String() string            { return proto.CompactTextString(m) }
func (*AssetRegister) ProtoMessage()               {}
func (*AssetRegister) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AssetRegister) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *AssetRegister) GetChaincode() string {
	if m != nil {
		return m.Chaincode
	}
	return ""
}

func (m *AssetRegister) GetAppid() string {
	if m != nil {
		return m.Appid
	}
	return ""
}

func (m *AssetRegister) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *AssetRegister) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type AssetQuery struct {
	Channel   string `protobuf:"bytes,1,opt,name=channel" json:"channel,omitempty"`
	Chaincode string `protobuf:"bytes,2,opt,name=chaincode" json:"chaincode,omitempty"`
	Appid     string `protobuf:"bytes,3,opt,name=appid" json:"appid,omitempty"`
	Key       string `protobuf:"bytes,4,opt,name=key" json:"key,omitempty"`
}

func (m *AssetQuery) Reset()                    { *m = AssetQuery{} }
func (m *AssetQuery) String() string            { return proto.CompactTextString(m) }
func (*AssetQuery) ProtoMessage()               {}
func (*AssetQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AssetQuery) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *AssetQuery) GetChaincode() string {
	if m != nil {
		return m.Chaincode
	}
	return ""
}

func (m *AssetQuery) GetAppid() string {
	if m != nil {
		return m.Appid
	}
	return ""
}

func (m *AssetQuery) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type Transaction struct {
	Channel    string `protobuf:"bytes,1,opt,name=channel" json:"channel,omitempty"`
	Chaincode  string `protobuf:"bytes,2,opt,name=chaincode" json:"chaincode,omitempty"`
	Ownerid    string `protobuf:"bytes,3,opt,name=ownerid" json:"ownerid,omitempty"`
	Receiverid string `protobuf:"bytes,4,opt,name=receiverid" json:"receiverid,omitempty"`
	Payload    string `protobuf:"bytes,5,opt,name=payload" json:"payload,omitempty"`
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Transaction) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *Transaction) GetChaincode() string {
	if m != nil {
		return m.Chaincode
	}
	return ""
}

func (m *Transaction) GetOwnerid() string {
	if m != nil {
		return m.Ownerid
	}
	return ""
}

func (m *Transaction) GetReceiverid() string {
	if m != nil {
		return m.Receiverid
	}
	return ""
}

func (m *Transaction) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type ResultsReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Payload string `protobuf:"bytes,2,opt,name=payload" json:"payload,omitempty"`
}

func (m *ResultsReply) Reset()                    { *m = ResultsReply{} }
func (m *ResultsReply) String() string            { return proto.CompactTextString(m) }
func (*ResultsReply) ProtoMessage()               {}
func (*ResultsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ResultsReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ResultsReply) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "stream.RegisterRequest")
	proto.RegisterType((*RegisterReply)(nil), "stream.RegisterReply")
	proto.RegisterType((*AssetEnroll)(nil), "stream.AssetEnroll")
	proto.RegisterType((*AssetRegister)(nil), "stream.AssetRegister")
	proto.RegisterType((*AssetQuery)(nil), "stream.AssetQuery")
	proto.RegisterType((*Transaction)(nil), "stream.Transaction")
	proto.RegisterType((*ResultsReply)(nil), "stream.ResultsReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for StreamServer service

type StreamServerClient interface {
	RegisterClient(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error)
	EnrollAsset(ctx context.Context, in *AssetEnroll, opts ...grpc.CallOption) (*ResultsReply, error)
	RegisterAsset(ctx context.Context, in *AssetRegister, opts ...grpc.CallOption) (*ResultsReply, error)
	TransactionAsset(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*ResultsReply, error)
	QueryAsset(ctx context.Context, in *AssetQuery, opts ...grpc.CallOption) (*ResultsReply, error)
}

type streamServerClient struct {
	cc *grpc.ClientConn
}

func NewStreamServerClient(cc *grpc.ClientConn) StreamServerClient {
	return &streamServerClient{cc}
}

func (c *streamServerClient) RegisterClient(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error) {
	out := new(RegisterReply)
	err := grpc.Invoke(ctx, "/stream.StreamServer/RegisterClient", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServerClient) EnrollAsset(ctx context.Context, in *AssetEnroll, opts ...grpc.CallOption) (*ResultsReply, error) {
	out := new(ResultsReply)
	err := grpc.Invoke(ctx, "/stream.StreamServer/EnrollAsset", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServerClient) RegisterAsset(ctx context.Context, in *AssetRegister, opts ...grpc.CallOption) (*ResultsReply, error) {
	out := new(ResultsReply)
	err := grpc.Invoke(ctx, "/stream.StreamServer/RegisterAsset", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServerClient) TransactionAsset(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*ResultsReply, error) {
	out := new(ResultsReply)
	err := grpc.Invoke(ctx, "/stream.StreamServer/TransactionAsset", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServerClient) QueryAsset(ctx context.Context, in *AssetQuery, opts ...grpc.CallOption) (*ResultsReply, error) {
	out := new(ResultsReply)
	err := grpc.Invoke(ctx, "/stream.StreamServer/QueryAsset", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for StreamServer service

type StreamServerServer interface {
	RegisterClient(context.Context, *RegisterRequest) (*RegisterReply, error)
	EnrollAsset(context.Context, *AssetEnroll) (*ResultsReply, error)
	RegisterAsset(context.Context, *AssetRegister) (*ResultsReply, error)
	TransactionAsset(context.Context, *Transaction) (*ResultsReply, error)
	QueryAsset(context.Context, *AssetQuery) (*ResultsReply, error)
}

func RegisterStreamServerServer(s *grpc.Server, srv StreamServerServer) {
	s.RegisterService(&_StreamServer_serviceDesc, srv)
}

func _StreamServer_RegisterClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServerServer).RegisterClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stream.StreamServer/RegisterClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServerServer).RegisterClient(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamServer_EnrollAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetEnroll)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServerServer).EnrollAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stream.StreamServer/EnrollAsset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServerServer).EnrollAsset(ctx, req.(*AssetEnroll))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamServer_RegisterAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetRegister)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServerServer).RegisterAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stream.StreamServer/RegisterAsset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServerServer).RegisterAsset(ctx, req.(*AssetRegister))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamServer_TransactionAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServerServer).TransactionAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stream.StreamServer/TransactionAsset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServerServer).TransactionAsset(ctx, req.(*Transaction))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamServer_QueryAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServerServer).QueryAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stream.StreamServer/QueryAsset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServerServer).QueryAsset(ctx, req.(*AssetQuery))
	}
	return interceptor(ctx, in, info, handler)
}

var _StreamServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stream.StreamServer",
	HandlerType: (*StreamServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterClient",
			Handler:    _StreamServer_RegisterClient_Handler,
		},
		{
			MethodName: "EnrollAsset",
			Handler:    _StreamServer_EnrollAsset_Handler,
		},
		{
			MethodName: "RegisterAsset",
			Handler:    _StreamServer_RegisterAsset_Handler,
		},
		{
			MethodName: "TransactionAsset",
			Handler:    _StreamServer_TransactionAsset_Handler,
		},
		{
			MethodName: "QueryAsset",
			Handler:    _StreamServer_QueryAsset_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stream.pro",
}

func init() { proto.RegisterFile("stream.pro", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 480 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xae, 0xf3, 0x57, 0x75, 0xd2, 0x40, 0x34, 0xb4, 0x60, 0x55, 0x08, 0x55, 0x16, 0x07, 0xc4,
	0xa1, 0x07, 0xb8, 0x20, 0x0e, 0x20, 0x8a, 0x78, 0x00, 0x52, 0x5e, 0x60, 0x71, 0xa6, 0x89, 0xd5,
	0xad, 0x77, 0x99, 0xdd, 0xa4, 0xf2, 0x99, 0x13, 0x8f, 0xc0, 0xf3, 0x70, 0xe2, 0xad, 0xd0, 0xfe,
	0x38, 0xb6, 0x53, 0x52, 0x24, 0xa4, 0xde, 0xe6, 0xfb, 0xc6, 0xe3, 0xef, 0x9b, 0xd9, 0x19, 0x00,
	0x63, 0x99, 0xc4, 0xf5, 0x99, 0x66, 0x85, 0xa3, 0x10, 0x67, 0x57, 0xf0, 0x70, 0x46, 0x8b, 0xc2,
	0x58, 0xe2, 0x19, 0x7d, 0x5b, 0x91, 0xb1, 0x88, 0x30, 0x58, 0x19, 0xe2, 0x34, 0x39, 0x4d, 0x5e,
	0x1c, 0xcc, 0x7c, 0x8c, 0x53, 0xe8, 0xeb, 0x9b, 0x79, 0xda, 0xf3, 0x94, 0x0b, 0x1d, 0xa3, 0x78,
	0x91, 0xf6, 0x03, 0xa3, 0x78, 0x81, 0xa7, 0x30, 0x16, 0x97, 0x97, 0x85, 0x2c, 0x84, 0x2d, 0x54,
	0x99, 0x0e, 0x7c, 0xa6, 0x4d, 0x65, 0xdf, 0x13, 0x98, 0x34, 0x6a, 0x5a, 0x56, 0x98, 0xc2, 0xfe,
	0x35, 0x19, 0x23, 0x16, 0x14, 0xe5, 0x6a, 0x88, 0x47, 0x30, 0x14, 0x5a, 0x17, 0xb5, 0x66, 0x00,
	0xf8, 0x18, 0x46, 0x42, 0xeb, 0x2b, 0xaa, 0xa2, 0x70, 0x44, 0x8e, 0xd7, 0x5c, 0x38, 0x3e, 0xc8,
	0x46, 0xe4, 0x7a, 0xc9, 0x89, 0x6d, 0x3a, 0x0c, 0xbd, 0xb8, 0x38, 0xfb, 0x95, 0xc0, 0xf8, 0x83,
	0x31, 0x64, 0x3f, 0x95, 0xac, 0xa4, 0x74, 0x1e, 0xf2, 0xa5, 0x28, 0x4b, 0x92, 0xb5, 0x87, 0x08,
	0xf1, 0x39, 0x4c, 0xf2, 0xa5, 0x28, 0xca, 0x5c, 0xcd, 0x49, 0x0b, 0xbb, 0x8c, 0x5e, 0xba, 0x24,
	0x3e, 0x85, 0x83, 0x0d, 0x11, 0x6d, 0x35, 0x04, 0xbe, 0x84, 0xe9, 0x06, 0xac, 0x89, 0x4d, 0x33,
	0x9a, 0x5b, 0xbc, 0x9b, 0xa9, 0x6b, 0x21, 0x98, 0x75, 0xa1, 0xf3, 0xa6, 0x45, 0x25, 0x95, 0x98,
	0xa7, 0xa3, 0xe0, 0x2d, 0xc2, 0xec, 0x47, 0x02, 0x13, 0xdf, 0x45, 0x3d, 0xd0, 0x3b, 0xfa, 0xe8,
	0x38, 0xec, 0x6d, 0x3b, 0xdc, 0x4c, 0xba, 0xdf, 0x9e, 0x74, 0xf4, 0x32, 0xf8, 0xab, 0x97, 0x61,
	0xd7, 0x8b, 0x04, 0xf0, 0x56, 0x3e, 0xaf, 0x88, 0xab, 0xfb, 0xf6, 0x91, 0xfd, 0x4c, 0x60, 0xfc,
	0x85, 0x45, 0x69, 0x44, 0xee, 0xb6, 0xea, 0xbf, 0xf5, 0x52, 0xd8, 0x57, 0x37, 0x25, 0xf1, 0x46,
	0xb1, 0x86, 0xf8, 0x0c, 0x80, 0x29, 0xa7, 0x62, 0xed, 0x93, 0x41, 0xba, 0xc5, 0xdc, 0x31, 0x89,
	0x73, 0x38, 0x9c, 0x91, 0x59, 0x49, 0x6b, 0xfe, 0xb5, 0xdf, 0xad, 0x7f, 0xf4, 0x3a, 0xff, 0x78,
	0xf5, 0xbb, 0x07, 0x87, 0x17, 0xfe, 0x3a, 0x2f, 0x88, 0xd7, 0xc4, 0x78, 0x0e, 0x0f, 0xea, 0x47,
	0xfe, 0x28, 0x0b, 0x2a, 0x2d, 0x3e, 0x39, 0x8b, 0xa7, 0xbc, 0x75, 0xbb, 0x27, 0xc7, 0xb7, 0x13,
	0x5a, 0x56, 0xd9, 0x1e, 0xbe, 0x85, 0x71, 0x58, 0x77, 0xff, 0x50, 0xf8, 0xa8, 0xfe, 0xae, 0x75,
	0x08, 0x27, 0x47, 0x4d, 0x71, 0xd3, 0x42, 0xb6, 0x87, 0xef, 0x9a, 0xab, 0x0d, 0xd5, 0xc7, 0x9d,
	0xea, 0x3a, 0xb7, 0xb3, 0xfe, 0x3d, 0x4c, 0x5b, 0xef, 0xb5, 0x65, 0xa0, 0x95, 0xd9, 0xf9, 0x83,
	0x37, 0x00, 0x7e, 0xb5, 0x42, 0x29, 0x76, 0xd4, 0x7d, 0x62, 0x57, 0xe5, 0xd7, 0x91, 0x66, 0x65,
	0xd5, 0xeb, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc7, 0xd9, 0x5e, 0x08, 0xfb, 0x04, 0x00, 0x00,
}
